package co.com.touresbalon.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2018-10-11T18:14:34.469-05:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebService(targetNamespace = "http://service.touresbalon.com.co/", name = "ClientesService")
@XmlSeeAlso({ObjectFactory.class})
public interface ClientesService {

    @WebMethod
    @RequestWrapper(localName = "consultarClientePorNumeroProducto", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorNumeroProducto")
    @ResponseWrapper(localName = "consultarClientePorNumeroProductoResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorNumeroProductoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaCliente consultarClientePorNumeroProducto(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaCliente filtro
    );

    @WebMethod
    @RequestWrapper(localName = "actualizarCliente", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarCliente")
    @ResponseWrapper(localName = "actualizarClienteResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ActualizarClienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoCliente actualizarCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        co.com.touresbalon.service.ClienteBO cliente
    );

    @WebMethod
    @RequestWrapper(localName = "crearCliente", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.CrearCliente")
    @ResponseWrapper(localName = "crearClienteResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.CrearClienteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoCliente crearCliente(
        @WebParam(name = "cliente", targetNamespace = "")
        co.com.touresbalon.service.ClienteBO cliente
    );

    @WebMethod
    @RequestWrapper(localName = "consultarClientePorFacturacion", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorFacturacion")
    @ResponseWrapper(localName = "consultarClientePorFacturacionResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorFacturacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaCliente consultarClientePorFacturacion(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaCliente filtro
    );

    @WebMethod
    @RequestWrapper(localName = "consultarClientePorIdentificacion", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorIdentificacion")
    @ResponseWrapper(localName = "consultarClientePorIdentificacionResponse", targetNamespace = "http://service.touresbalon.com.co/", className = "co.com.touresbalon.service.ConsultarClientePorIdentificacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public co.com.touresbalon.service.ResultadoConsultaCliente consultarClientePorIdentificacion(
        @WebParam(name = "filtro", targetNamespace = "")
        co.com.touresbalon.service.FiltroConsultaCliente filtro
    );
}
