package co.com.touresbalon.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2018-10-11T18:14:34.572-05:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebServiceClient(name = "ServicioClientes", 
                  wsdlLocation = "file:/Users/arkazero/workspaceFuse11/OMS-Mod-Clientes/src/main/resources/ServicioClientes.wsdl",
                  targetNamespace = "http://service.touresbalon.com.co/") 
public class ServicioClientes extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.touresbalon.com.co/", "ServicioClientes");
    public final static QName ClientesServicePort = new QName("http://service.touresbalon.com.co/", "ClientesServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/arkazero/workspaceFuse11/OMS-Mod-Clientes/src/main/resources/ServicioClientes.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioClientes.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/arkazero/workspaceFuse11/OMS-Mod-Clientes/src/main/resources/ServicioClientes.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioClientes(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioClientes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioClientes() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServicioClientes(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioClientes(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioClientes(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ClientesService
     */
    @WebEndpoint(name = "ClientesServicePort")
    public ClientesService getClientesServicePort() {
        return super.getPort(ClientesServicePort, ClientesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientesService
     */
    @WebEndpoint(name = "ClientesServicePort")
    public ClientesService getClientesServicePort(WebServiceFeature... features) {
        return super.getPort(ClientesServicePort, ClientesService.class, features);
    }

}
